### ISSUE TITLE
Is everything ok?

### ISSUE THREAD

**Issue by Ratstail91** [hiperiondev/hiperiondev#1]
Hey!

I wanted to check if everything was ok - I noticed a little while ago that you dropped out of the server, and I have a habit of caring about people in there (odd phrasing, but it's true).

I hope things are going well.

(P.S. sorry for posting in your issues, I figured digging up your email was a step too far.)

**Comment by hiperiondev** [comment]
Hey!
Everything is fine. Just busy with work and domestic matters.
When I'm done with everything I'll be back!

**Comment by Ratstail91** [comment]
Awesome, good to know. Best of luck!!
